### ISSUE TITLE
Cannot return gd.Error

### ISSUE THREAD

**Issue by AllenDang** [grow-graphics/gd#24]
Go code is
```go
package main

import (
	"grow.graphics/gd"
	"grow.graphics/gd/gdextension"
)

type Test struct {
	gd.Class[Test, gd.Object]
}

func (t *Test) GetError(context gd.Context) gd.Error {
	return gd.Ok
}

func main() {
	godot, ok := gdextension.Link()
	if !ok {
		return
	}

	gd.Register[Test](godot)
}
```

main.gd
```gdscript
extends Node


func _ready() -> void:
	var test = Test.new()
	print(test.GetError())
```

error message is
```
Godot Engine v4.2.2.stable.official.15073afe3 - https://godotengine.org
Vulkan API 1.2.231 - Forward+ - Using Vulkan Device #0: Apple - Apple M1 Max
 
{ "hello": 123 }
panic: gd.Variant: unsupported type gd.Error

goroutine 17 [running, locked to thread]:
grow.graphics/gd/internal.Context.Variant({{0x1135cc100?, 0x14000766060?}, 0x11459f9a0?}, {0x1135cc100, 0x14000144088})
        /Users/allen/go/pkg/mod/grow.graphics/gd@v0.0.0-20240529060545-d7995a504196/internal/variant_conversions.go:194 +0x1b7c
grow.graphics/gd.registerMethods.func1({{0x2, 0x14000766060}, 0x11459f9a0}, {0x1136fe2a0, 0x14000766030}, {0x1145fbac0, 0x0, 0x140006b39e0?})
        /Users/allen/go/pkg/mod/grow.graphics/gd@v0.0.0-20240529060545-d7995a504196/register_methods.go:52 +0x3ac
grow.graphics/gd/gdextension.method_call(0x140006efe28?, 0x4, 0x16db75c08, 0x0, 0x16db75ac0, 0x16db75a70)
        /Users/allen/go/pkg/mod/grow.graphics/gd@v0.0.0-20240529060545-d7995a504196/gdextension/gdextension_interface.go:2562 +0x26c
signal: abort trap
```

**Comment by Splizard** [comment]
Fixed, godot errors are just `gd.Int` but we can support the type specifically.
